apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: external-dns
  namespace: '{{ .Release.Namespace }}'
  annotations:
    azure.workload.identity~1client-id: '{{ .Values.credentials.userAssignedIdentityID }}'
