apiVersion: v1
data:
  .dockerconfigjson: e30K
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    hypershift.openshift.io/safe-to-delete-with-cluster: "true"
  name: pull-secret
  namespace: '{{ .Release.Namespace }}'
type: kubernetes.io/dockerconfigjson
