apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: null
  name: operator
  namespace: '{{ .Release.Namespace }}'
spec:
  endpoints:
  - interval: 30s
    port: metrics
  jobLabel: component
  namespaceSelector: {}
  selector:
    matchLabels:
      name: operator
